### PR TITLE
Add AssetLoadRequestAwaiter

### PR DESCRIPTION
**Pull request by ArthurRibeirox**

### CODE REVIEW

**Review by caioteixeira — APPROVED** [review]
This seems good enough for now. I think the ideal solution would be to provide async methods on the provider interface, those methods would return Task<T> objects so we could just use the await keyword. :)

**Comment by caioteixeira** [comment]
#3 :)

**Comment by caioteixeira** [comment]
Actually, I understood it wrong D: It already enables us to use async/await 👍 I think we should also add this change to SceneLoadRequest :)

**Review by FernandoGavinhosDosSantos — APPROVED** [review]
Agreed with @caioteixeira. My only doubt would be about how difficult it would be to migrate this implementation into tasks once some projects have started to use this awaiter. Maybe we should avoid taking too long to do this.

**Comment by FernandoGavinhosDosSantos** [comment]
Forget about it. I didn't read the last comment.

**Pull request merged**
